blog/urls.py
from django.urls import path
from .views import (
    BlogListView, BlogDetailView,
    BlogCreateView, BlogUpdateView,
    BlogDeleteView)

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path(
        'post/<int:pk>/delete/',
        BlogDeleteView.as_view(),
        name='post_delete'
    ),

]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path('sentry-debug/', trigger_error),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    # blog app url
    path('', include('blog.urls', namespace='blog')),
    # api posting url
    path('', include('blog.api.urls')),
    # contact app url
    path('contact/', include('contact.urls', namespace='contact')),
    # search app url
    path('', include('search.urls')),
    path('', include('django_prometheus.urls')),
]

search/urls.py
from django.urls import path
from . import views as search_views


urlpatterns = [
    path('search/', search_views.search, name='search'),
 ]

search/models.py
from django.db import models

search/views.py
from django.shortcuts import render
from blog.models import Post


def search(request):
    q = request.GET.get('q')
    posts = Post.objects.filter(title__search=q)

    return render(request, 'search/search.html', {'posts': posts})

templates/search/search.html
{% extends 'base.html' %}

{% block content %}
{% if posts %}
   <h1>Result set...</h1>
   {% for post in posts %}
        <div class="post-entry">
            <h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.body }}</p>
        </div>
     
    {% endfor %}
{% else %}
  <h1>No such post available</h1>
{% endif %}    
<hr>
<h2><a href="{% url 'blog:home' %}">Back</a></h2>
{% endblock content %}