blog/urls.py
from django.urls import path
from .views import (
    BlogListView, BlogDetailView,
    BlogCreateView, BlogUpdateView,
    BlogDeleteView)

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path(
        'post/<int:pk>/delete/',
        BlogDeleteView.as_view(),
        name='post_delete'
    ),

]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path('sentry-debug/', trigger_error),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    # blog app url
    path('', include('blog.urls', namespace='blog')),
    # api posting url
    path('', include('blog.api.urls')),
    # contact app url
    path('contact/', include('contact.urls', namespace='contact')),
    # search app url
    path('', include('search.urls')),
    path('', include('django_prometheus.urls')),
]

contact/urls.py
from django.urls import path
from contact.views import ContactView

app_name = 'contact'

urlpatterns = [
    # contact app url
    path('contact/', ContactView.as_view(), name="contact"),
]

templates/base.html
<!-- templates/base.html -->
{% load static %}
<html>
    <head>
        <title> blog</title>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:rel="stylesheet">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
            <div class="nav-left">
                <h1><a href="{% url 'blog:home' %}">Available posts</a></h1>
            </div>
            <div class="nav-left">
                <h1><a href="{% url 'contact:contact' %}">Contact us</a></h1>
            </div>
            {% if request.user.is_authenticated %}
            <div class="nav-right">
                <a href="{% url 'blog:post_new' %}">+ New Blog Post</a>
            </div>
            {% endif %}
        </header>
        <header>
        {% if request.user.is_authenticated %}
            <div class="nav-left">
                <p>Hi {{ user.username }}!</p>
                <p><a href="{% url 'logout' %}">Log out</a></p>
            </div>
        {% else %}
        <div class="nav-left">
            <p>You are not logged in.</p>
            <p><a href="{% url 'login' %}">Log In</a></p>
            <p><a href="{% url 'signup' %}">Sign Up</a></p>
        </div>
        {% endif %}
        </header>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>